export const blogs = [
  {
    id: 1,
    slug: "bmi-calculator-guide",
    title: "BMI Calculator Guide",
    image: "/Blogs/bmi.webp",
    description: "Learn everything about BMI Calculator.",
    date: "July 25, 2026",
    category: "Calculator",
  },
  {
    id: 2,
    slug: "age-calculator-guide",
    title: "Age Calculator Guide",
    image: "/Blogs/age.webp",
    description: "Calculate your exact age instantly.",
    date: "July 26, 2026",
    category: "Calculator",
  },
  {
    id: 3,
    slug: "percentage-calculator-guide",
    title: "Percentage Calculator Guide",
    image: "/Blogs/percentage.webp",
    description: "Learn how to calculate percentages easily.",
    date: "July 27, 2026",
    category: "Calculator",
  },
  {
    id: 4,
    slug: "word-counter-guide",
    title: "Word Counter Guide",
    image: "/Blogs/word-counter.webp",
    description: "Count words, characters, and paragraphs instantly.",
    date: "July 28, 2026",
    category: "Utility",
  },
  {
    id: 5,
    slug: "password-generator-guide",
    title: "Password Generator Guide",
    image: "/Blogs/password.webp",
    description: "Create strong and secure passwords online.",
    date: "July 29, 2026",
    category: "Utility",
  },
  {
    id: 6,
    slug: "qr-code-generator-guide",
    title: "QR Code Generator Guide",
    image: "/Blogs/qr.webp",
    description: "Generate QR codes for websites, text, and more.",
    date: "July 30, 2026",
    category: "Utility",
  },
  {
    id: 7,
    slug: "image-resizer-guide",
    title: "Image Resizer Guide",
    image: "/Blogs/image-resizer.webp",
    description: "Resize images quickly without losing quality.",
    date: "July 31, 2026",
    category: "Image",
  },
  {
    id: 8,
    slug: "image-compressor-guide",
    title: "Image Compressor Guide",
    image: "/Blogs/image-compressor.webp",
    description: "Compress images while maintaining quality.",
    date: "August 1, 2026",
    category: "Image",
  },
  {
    id: 9,
    slug: "image-cropper-guide",
    title: "Image Cropper Guide",
    image: "/Blogs/image-cropper.webp",
    description: "Crop images to the perfect size online.",
    date: "August 2, 2026",
    category: "Image",
  },
  {
    id: 10,
    slug: "png-to-jpg-guide",
    title: "PNG to JPG Guide",
    image: "/Blogs/png-to-jpg.webp",
    description: "Convert PNG images to JPG effortlessly.",
    date: "August 3, 2026",
    category: "Image",
  },
  {
    id: 11,
    slug: "jpg-to-png-guide",
    title: "JPG to PNG Guide",
    image: "/Blogs/jpg-to-png.webp",
    description: "Convert JPG images into PNG format.",
    date: "August 4, 2026",
    category: "Image",
  },
  {
    id: 12,
    slug: "image-converter-guide",
    title: "Image Converter Guide",
    image: "/Blogs/image-converter.webp",
    description: "Convert images between popular formats.",
    date: "August 5, 2026",
    category: "Image",
  },
  {
    id: 13,
    slug: "pdf-to-word-guide",
    title: "PDF to Word Guide",
    image: "/Blogs/pdf-to-word.webp",
    description: "Convert PDF files into editable Word documents.",
    date: "August 6, 2026",
    category: "PDF",
  },
  {
    id: 14,
    slug: "word-to-pdf-guide",
    title: "Word to PDF Guide",
    image: "/Blogs/word-to-pdf.webp",
    description: "Convert Word documents into PDF files.",
    date: "August 7, 2026",
    category: "PDF",
  },
  {
    id: 15,
    slug: "pdf-merger-guide",
    title: "PDF Merger Guide",
    image: "/Blogs/pdf-merger.webp",
    description: "Merge multiple PDF files into one document.",
    date: "August 8, 2026",
    category: "PDF",
  },
  {
    id: 16,
    slug: "pdf-splitter-guide",
    title: "PDF Splitter Guide",
    image: "/Blogs/pdf-splitter.webp",
    description: "Split PDF files into separate pages easily.",
    date: "August 9, 2026",
    category: "PDF",
  },
  {
    id: 17,
    slug: "pdf-to-jpg-guide",
    title: "PDF to JPG Guide",
    image: "/Blogs/pdf-to-jpg.webp",
    description: "Convert PDF pages into JPG images.",
    date: "August 10, 2026",
    category: "PDF",
  },
  {
    id: 18,
    slug: "jpg-to-pdf-guide",
    title: "JPG to PDF Guide",
    image: "/Blogs/jpg-to-pdf.webp",
    description: "Convert JPG images into PDF documents.",
    date: "August 11, 2026",
    category: "PDF",
  },
  {
    id: 19,
    slug: "json-formatter-guide",
    title: "JSON Formatter Guide",
    image: "/Blogs/json-formatter.webp",
    description: "Format and beautify JSON data with ease.",
    date: "August 12, 2026",
    category: "Developer",
  },
  {
    id: 20,
    slug: "json-validator-guide",
    title: "JSON Validator Guide",
    image: "/Blogs/json-validator.webp",
    description: "Validate JSON data and fix syntax errors.",
    date: "August 13, 2026",
    category: "Developer",
  },
  {
    id: 21,
    slug: "base64-encoder-guide",
    title: "Base64 Encoder Guide",
    image: "/Blogs/base64-encoder.webp",
    description: "Encode text and files into Base64 format.",
    date: "August 14, 2026",
    category: "Developer",
  },
  {
    id: 22,
    slug: "base64-decoder-guide",
    title: "Base64 Decoder Guide",
    image: "/Blogs/base64-decoder.webp",
    description: "Decode Base64 strings quickly and accurately.",
    date: "August 15, 2026",
    category: "Developer",
  },
  {
    id: 23,
    slug: "html-minifier-guide",
    title: "HTML Minifier Guide",
    image: "/Blogs/html-minifier.webp",
    description: "Minify HTML code for faster website performance.",
    date: "August 16, 2026",
    category: "Developer",
  },
  {
    id: 24,
    slug: "css-minifier-guide",
    title: "CSS Minifier Guide",
    image: "/Blogs/css-minifier.webp",
    description: "Reduce CSS file size for better loading speed.",
    date: "August 17, 2026",
    category: "Developer",
  },
  {
    id: 25,
    slug: "javascript-minifier-guide",
    title: "JavaScript Minifier Guide",
    image: "/Blogs/javascript-minifier.webp",
    description: "Optimize JavaScript code by minifying it.",
    date: "August 18, 2026",
    category: "Developer",
  },
  {
    id: 26,
    slug: "url-encoder-guide",
    title: "URL Encoder Guide",
    image: "/Blogs/url-encoder.webp",
    description: "Encode URLs safely for web applications.",
    date: "August 19, 2026",
    category: "Developer",
  },
  {
    id: 27,
    slug: "url-decoder-guide",
    title: "URL Decoder Guide",
    image: "/Blogs/url-decoder.webp",
    description: "Decode encoded URLs into readable text.",
    date: "August 20, 2026",
    category: "Developer",
  },
  {
    id: 28,
    slug: "pdf-tools-guide",
    title: "PDF Tools Guide",
    image: "/Blogs/pdf-tools.webp",
    description: "Discover the best online PDF tools for daily tasks.",
    date: "August 21, 2026",
    category: "PDF",
  },
  {
    id: 29,
    slug: "image-tools-guide",
    title: "Image Tools Guide",
    image: "/Blogs/image-tools.webp",
    description: "Explore the best online image editing tools.",
    date: "August 22, 2026",
    category: "Image",
  },
  {
    id: 30,
    slug: "developer-tools-guide",
    title: "Developer Tools Guide",
    image: "/Blogs/developer-tools.webp",
    description: "Essential online developer tools for coding productivity.",
    date: "August 23, 2026",
    category: "Developer",
  },
  {
    id: 31,
    slug: "emi-calculator-guide",
    title: "EMI Calculator Guide",
    image: "/Blogs/emi.webp",
    description: "An EMI Calculator helps you work out the Equated Monthly Installment you'll pay on a loan, based on the pri...",
    date: "August 3, 2026",
    category: "Calculator",
  },
  {
    id: 32,
    slug: "compound-interest-calculator-guide",
    title: "Compound Interest Calculator Guide",
    image: "/Blogs/percentage.webp",
    description: "A Compound Interest Calculator estimates how an investment or deposit grows over time when interest is earn...",
    date: "August 3, 2026",
    category: "Calculator",
  },
  {
    id: 33,
    slug: "simple-interest-calculator-guide",
    title: "Simple Interest Calculator Guide",
    image: "/Blogs/percentage.webp",
    description: "A Simple Interest Calculator calculates interest earned or owed based only on the original principal amount...",
    date: "August 3, 2026",
    category: "Calculator",
  },
  {
    id: 34,
    slug: "gst-calculator-guide",
    title: "GST Calculator Guide",
    image: "/Blogs/percentage.webp",
    description: "A GST Calculator helps you quickly add or remove Goods and Services Tax from a given amount, showing both t...",
    date: "August 3, 2026",
    category: "Calculator",
  },
  {
    id: 35,
    slug: "sales-tax-calculator-guide",
    title: "Sales Tax Calculator Guide",
    image: "/Blogs/percentage.webp",
    description: "A Sales Tax Calculator computes the total price of an item after adding the applicable sales tax rate, or w...",
    date: "August 3, 2026",
    category: "Calculator",
  },
  {
    id: 36,
    slug: "discount-calculator-guide",
    title: "Discount Calculator Guide",
    image: "/Blogs/percentage.webp",
    description: "A Discount Calculator helps you quickly find the final price of an item after a percentage discount is appl...",
    date: "August 3, 2026",
    category: "Calculator",
  },
  {
    id: 37,
    slug: "tip-calculator-guide",
    title: "Tip Calculator Guide",
    image: "/Blogs/percentage.webp",
    description: "A Tip Calculator helps you quickly work out how much to tip at a restaurant and how to split the total bill...",
    date: "August 3, 2026",
    category: "Calculator",
  },
  {
    id: 38,
    slug: "profit-margin-calculator-guide",
    title: "Profit Margin Calculator Guide",
    image: "/Blogs/percentage.webp",
    description: "A Profit Margin Calculator helps businesses determine profit, profit margin percentage, and markup based on...",
    date: "August 3, 2026",
    category: "Calculator",
  },
  {
    id: 39,
    slug: "break-even-calculator-guide",
    title: "Break-Even Point Calculator Guide",
    image: "/Blogs/percentage.webp",
    description: "A Break-Even Point Calculator determines how many units of a product you need to sell, or how much revenue ...",
    date: "August 3, 2026",
    category: "Calculator",
  },
  {
    id: 40,
    slug: "sip-calculator-guide",
    title: "SIP Calculator Guide",
    image: "/Blogs/percentage.webp",
    description: "A SIP Calculator projects the future value of a Systematic Investment Plan, showing how regular monthly inv...",
    date: "August 3, 2026",
    category: "Calculator",
  },
  {
    id: 41,
    slug: "mortgage-calculator-guide",
    title: "Mortgage Calculator Guide",
    image: "/Blogs/percentage.webp",
    description: "A Mortgage Calculator estimates your monthly home loan payment based on the loan amount, interest rate, and...",
    date: "August 3, 2026",
    category: "Calculator",
  },
  {
    id: 42,
    slug: "bmr-calculator-guide",
    title: "BMR Calculator Guide",
    image: "/Blogs/bmi.webp",
    description: "A BMR Calculator estimates your Basal Metabolic Rate - the number of calories your body burns at rest just ...",
    date: "August 3, 2026",
    category: "Calculator",
  },
  {
    id: 43,
    slug: "calorie-calculator-guide",
    title: "Calorie Calculator Guide",
    image: "/Blogs/bmi.webp",
    description: "A Calorie Calculator estimates your total daily calorie needs based on your BMR and activity level, helping...",
    date: "August 3, 2026",
    category: "Calculator",
  },
  {
    id: 44,
    slug: "body-fat-calculator-guide",
    title: "Body Fat Calculator Guide",
    image: "/Blogs/bmi.webp",
    description: "A Body Fat Calculator estimates the percentage of your total body weight that is made up of fat, using the ...",
    date: "August 3, 2026",
    category: "Calculator",
  },
  {
    id: 45,
    slug: "ideal-weight-calculator-guide",
    title: "Ideal Weight Calculator Guide",
    image: "/Blogs/bmi.webp",
    description: "An Ideal Weight Calculator estimates a healthy target body weight range based on your height and biological...",
    date: "August 3, 2026",
    category: "Calculator",
  },
  {
    id: 46,
    slug: "gpa-calculator-guide",
    title: "GPA Calculator Guide",
    image: "/Blogs/percentage.webp",
    description: "A GPA Calculator computes your Grade Point Average by converting your letter or numeric grades into grade p...",
    date: "August 3, 2026",
    category: "Calculator",
  },
  {
    id: 47,
    slug: "average-calculator-guide",
    title: "Average Calculator Guide",
    image: "/Blogs/percentage.webp",
    description: "An Average Calculator computes the mean, sum, minimum, and maximum of a list of numbers you enter, making q...",
    date: "August 3, 2026",
    category: "Calculator",
  },
  {
    id: 48,
    slug: "percentage-change-calculator-guide",
    title: "Percentage Change Calculator Guide",
    image: "/Blogs/percentage.webp",
    description: "A Percentage Change Calculator determines the percentage increase or decrease between an original value and...",
    date: "August 3, 2026",
    category: "Calculator",
  },
  {
    id: 49,
    slug: "date-difference-calculator-guide",
    title: "Date Difference Calculator Guide",
    image: "/Blogs/age.webp",
    description: "A Date Difference Calculator calculates the exact number of days, weeks, months, or years between two dates.",
    date: "August 3, 2026",
    category: "Calculator",
  },
  {
    id: 50,
    slug: "time-duration-calculator-guide",
    title: "Time Duration Calculator Guide",
    image: "/Blogs/age.webp",
    description: "A Time Duration Calculator calculates the exact duration between two times, in hours, minutes, and seconds.",
    date: "August 3, 2026",
    category: "Calculator",
  },
  {
    id: 51,
    slug: "length-converter-guide",
    title: "Length Converter Guide",
    image: "/Blogs/percentage.webp",
    description: "A Length Converter instantly converts measurements between units like meters, feet, inches, miles, and kilo...",
    date: "August 3, 2026",
    category: "Calculator",
  },
  {
    id: 52,
    slug: "weight-converter-guide",
    title: "Weight Converter Guide",
    image: "/Blogs/percentage.webp",
    description: "A Weight Converter instantly converts values between weight units like kilograms, pounds, ounces, and grams.",
    date: "August 3, 2026",
    category: "Calculator",
  },
  {
    id: 53,
    slug: "temperature-converter-guide",
    title: "Temperature Converter Guide",
    image: "/Blogs/percentage.webp",
    description: "A Temperature Converter instantly converts values between Celsius, Fahrenheit, and Kelvin temperature scales.",
    date: "August 3, 2026",
    category: "Calculator",
  },
  {
    id: 54,
    slug: "grammar-checker-guide",
    title: "Grammar Checker Guide",
    image: "/Blogs/word-counter.webp",
    description: "A Grammar Checker scans your text for grammar, spelling, and punctuation mistakes, offering suggestions to ...",
    date: "August 3, 2026",
    category: "Utility",
  },
  {
    id: 55,
    slug: "language-translator-guide",
    title: "Language Translator Guide",
    image: "/Blogs/word-counter.webp",
    description: "A Language Translator instantly converts text from one language into another, supporting communication and ...",
    date: "August 3, 2026",
    category: "Utility",
  },
  {
    id: 56,
    slug: "text-to-speech-converter-guide",
    title: "Text to Speech Converter Guide",
    image: "/Blogs/word-counter.webp",
    description: "A Text to Speech Converter transforms written text into natural-sounding spoken audio, directly in your bro...",
    date: "August 3, 2026",
    category: "Utility",
  },
  {
    id: 57,
    slug: "speech-to-text-converter-guide",
    title: "Speech to Text Converter Guide",
    image: "/Blogs/word-counter.webp",
    description: "A Speech to Text Converter transcribes spoken words captured through your microphone into written text in r...",
    date: "August 3, 2026",
    category: "Utility",
  },
  {
    id: 58,
    slug: "text-summarizer-guide",
    title: "AI Text Summarizer Guide",
    image: "/Blogs/developer-tools.webp",
    description: "An AI Text Summarizer uses artificial intelligence to condense long articles, essays, or documents into sho...",
    date: "August 3, 2026",
    category: "AI Tools",
  },
  {
    id: 59,
    slug: "paraphrasing-tool-guide",
    title: "AI Paraphrasing Tool Guide",
    image: "/Blogs/developer-tools.webp",
    description: "An AI Paraphrasing Tool rewrites sentences or paragraphs in a different tone or style while preserving the ...",
    date: "August 3, 2026",
    category: "AI Tools",
  },
  {
    id: 60,
    slug: "essay-generator-guide",
    title: "AI Essay Generator Guide",
    image: "/Blogs/developer-tools.webp",
    description: "An AI Essay Generator creates a well-structured essay on any given topic, complete with an introduction, bo...",
    date: "August 3, 2026",
    category: "AI Tools",
  },
  {
    id: 61,
    slug: "content-generator-guide",
    title: "AI Content Generator Guide",
    image: "/Blogs/developer-tools.webp",
    description: "An AI Content Generator creates blog intros, product descriptions, and ad copy instantly based on a short p...",
    date: "August 3, 2026",
    category: "AI Tools",
  },
  {
    id: 62,
    slug: "resume-analyzer-guide",
    title: "AI Resume Analyzer Guide",
    image: "/Blogs/developer-tools.webp",
    description: "An AI Resume Analyzer reviews your resume and provides feedback on strengths, weaknesses, and specific impr...",
    date: "August 3, 2026",
    category: "AI Tools",
  },
  {
    id: 63,
    slug: "cover-letter-generator-guide",
    title: "AI Cover Letter Generator Guide",
    image: "/Blogs/developer-tools.webp",
    description: "An AI Cover Letter Generator creates a personalized cover letter for a specific job application in seconds,...",
    date: "August 3, 2026",
    category: "AI Tools",
  },
  {
    id: 64,
    slug: "email-reply-generator-guide",
    title: "AI Email Reply Generator Guide",
    image: "/Blogs/developer-tools.webp",
    description: "An AI Email Reply Generator creates a smart, ready-to-send reply to any email based on the content and tone...",
    date: "August 3, 2026",
    category: "AI Tools",
  },
  {
    id: 65,
    slug: "meeting-notes-summarizer-guide",
    title: "AI Meeting Notes Summarizer Guide",
    image: "/Blogs/developer-tools.webp",
    description: "An AI Meeting Notes Summarizer turns a meeting transcript into a clear summary of key points, decisions mad...",
    date: "August 3, 2026",
    category: "AI Tools",
  },
  {
    id: 66,
    slug: "caption-generator-guide",
    title: "AI Caption & Hashtag Generator Guide",
    image: "/Blogs/developer-tools.webp",
    description: "An AI Caption & Hashtag Generator creates catchy social media captions and relevant hashtags based on your ...",
    date: "August 3, 2026",
    category: "AI Tools",
  },
  {
    id: 67,
    slug: "slogan-generator-guide",
    title: "AI Slogan & Tagline Generator Guide",
    image: "/Blogs/developer-tools.webp",
    description: "An AI Slogan & Tagline Generator creates catchy, memorable slogans and taglines for your business or brand ...",
    date: "August 3, 2026",
    category: "AI Tools",
  },
  {
    id: 68,
    slug: "best-free-pdf-tools-2026-guide",
    title: "10 Best Free PDF Tools You Should Bookmark Guide",
    image: "/Blogs/pdf-tools.webp",
    description: "This guide rounds up the most useful free PDF tools for everyday tasks - merging, splitting, converting, an...",
    date: "August 3, 2026",
    category: "PDF",
  },
  {
    id: 69,
    slug: "reduce-image-file-size-without-losing-quality-guide",
    title: "How to Reduce Image File Size Without Losing Quality Guide",
    image: "/Blogs/image-compressor.webp",
    description: "This guide explains practical techniques for shrinking image file sizes for faster websites and easier shar...",
    date: "August 3, 2026",
    category: "Image",
  },
  {
    id: 70,
    slug: "json-vs-xml-which-format-guide",
    title: "JSON vs XML: Which Data Format Should You Use? Guide",
    image: "/Blogs/json-formatter.webp",
    description: "This guide compares JSON and XML, two of the most widely used data interchange formats, to help you decide ...",
    date: "August 3, 2026",
    category: "Developer",
  },
  {
    id: 71,
    slug: "emi-vs-sip-which-to-calculate-guide",
    title: "EMI vs SIP: Which Should You Calculate Before Investing? Guide",
    image: "/Blogs/percentage.webp",
    description: "This guide explains the difference between EMI (loan repayment) and SIP (investment) calculations, helping ...",
    date: "August 3, 2026",
    category: "Calculator",
  },
  {
    id: 72,
    slug: "ideal-body-weight-why-it-matters-guide",
    title: "How to Calculate Your Ideal Body Weight and Why It Matters Guide",
    image: "/Blogs/bmi.webp",
    description: "This guide explains what 'ideal body weight' means, how it's calculated, and how to use it alongside other ...",
    date: "August 3, 2026",
    category: "Calculator",
  },
  {
    id: 73,
    slug: "simple-vs-compound-interest-difference-guide",
    title: "Simple Interest vs Compound Interest: What's the Difference? Guide",
    image: "/Blogs/percentage.webp",
    description: "This guide breaks down the key differences between simple interest and compound interest, and why the disti...",
    date: "August 3, 2026",
    category: "Calculator",
  },
  {
    id: 74,
    slug: "best-free-ai-writing-tools-guide",
    title: "5 Free AI Writing Tools That Save You Hours Every Week Guide",
    image: "/Blogs/developer-tools.webp",
    description: "This guide highlights five free AI-powered writing tools that can speed up everyday writing tasks, from sum...",
    date: "August 3, 2026",
    category: "AI Tools",
  },
  {
    id: 75,
    slug: "convert-file-formats-online-safely-guide",
    title: "How to Convert File Formats Online Safely (No Software Needed) Guide",
    image: "/Blogs/pdf-tools.webp",
    description: "This guide covers how to safely convert between common file formats - like PDF to Word, JPG to PNG, or PDF ...",
    date: "August 3, 2026",
    category: "PDF",
  },
  {
    id: 76,
    slug: "gst-calculation-for-small-businesses-guide",
    title: "GST Calculation Explained: A Simple Guide for Small Businesses Guide",
    image: "/Blogs/percentage.webp",
    description: "This guide walks small business owners through the basics of GST calculation - how to add it to invoices, h...",
    date: "August 3, 2026",
    category: "Calculator",
  },
  {
    id: 77,
    slug: "how-password-generators-keep-you-safe-guide",
    title: "How Password Generators Keep Your Accounts Safe Guide",
    image: "/Blogs/password.webp",
    description: "This guide explains how password generators create strong, random passwords, and why using one significantl...",
    date: "August 3, 2026",
    category: "Utility",
  },
  {
    id: 78,
    slug: "unit-converters-metric-vs-imperial-guide",
    title: "Unit Converters 101: Metric vs Imperial Explained Guide",
    image: "/Blogs/percentage.webp",
    description: "This guide explains the key differences between the metric and imperial measurement systems, and how unit c...",
    date: "August 3, 2026",
    category: "Calculator",
  },
  {
    id: 79,
    slug: "write-cover-letter-that-gets-noticed-guide",
    title: "How to Write a Cover Letter That Gets Noticed (with AI Help) Guide",
    image: "/Blogs/developer-tools.webp",
    description: "This guide covers the key elements of an effective cover letter, and how an AI cover letter generator can h...",
    date: "August 3, 2026",
    category: "AI Tools",
  },
  {
    id: 80,
    slug: "why-developers-need-code-minifiers-guide",
    title: "Why Every Developer Needs a Code Minifier Guide",
    image: "/Blogs/developer-tools.webp",
    description: "This guide explains what code minification is, why it matters for website performance, and how free online ...",
    date: "August 3, 2026",
    category: "Developer",
  }
];